name: Test Rust

on:
  push:
    branches: [*]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:

  build:
    name: Test Rust windows stable
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        dummio: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache Cargo output
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "desktop"
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - name: Run tests with image tests
        run: cargo test -p tests --locked --no-fail-fast --features imgtests,lzma,jpegxr stage3d
        env:
          RUST_LOG: 'wgpu=trace'
          XDG_RUNTIME_DIR: '' # dummy value, just to silence warnings about it missing
