name: Update AVM2 implementation report on website

on:
  push:
    branches: [ master ]
  # FIXME - remove before merging
  pull_request:
    branches: [master]

jobs:
  crowdin:
    runs-on: ubuntu-latest

    if: github.repository == 'ruffle-rs/ruffle'

    strategy:
      max-parallel: 1 # Should be 1 to avoid parallel builds
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run website update script
        run: |
          ./update-website.sh